title = 'Ivor Thibodo'
baseURL = 'https://mlo.io'
languageCode = 'en-us'
copyright = 'Ivor Thibodo'
timeZone = 'America/Chicago'

enableRobotsTXT = true
cleanDestinationDir = true

[params]
description = 'Software Engineer passionate about DevOps and Open Source.'

[params.hero]
id = 'main'
url = 'https://unsplash.com/photos/a-lake-surrounded-by-mountains-and-trees-vNVwg35VZrg'
credit = 'Philipp DÃ¼sel'

[frontmatter]
date = [':filename', ':default']

[taxonomies]
category = 'categories'

[permalinks.page]
posts = '/blog/:year/:month/:day/:slug/'
[permalinks.term]
categories = '/blog/category/:slug/'

[outputs]
home = ['html', 'rss', 'json']
section = ['html']
term = ['html']
taxonomy = ['html']

[outputFormats.rss]
baseName = 'feed'
[outputFormats.json]
baseName = 'feed'

[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'layouts/.*'
target = '(css|styles|scss|sass)'
